# 服务端口
server:
  port: 8303

# 服务名
spring:
  application:
    name: service-activity
  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_activity?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 扫描mapper
  mapper-locations: classpath:com/simon/classroom/activity/mapper/xml/*.xml
